services:
  db:
    image: postgres
    container_name: agregador_de_investimentos_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agregador_de_investimentos
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: agregador_de_investimentos_redis
    ports:
      - "6379:6379"

volumes:
  postgres-data: